[package]
name = "kenken_solver"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutohedron = "0"
derive-getters = "0"
itertools = "0"
rand = "0"
colored = "2"